### ISSUE TITLE
NullPointerException on join

### ISSUE THREAD

**Issue by en3my** [BattlePluginsDev/BattleArena#9] opened 2015-01-20 20:46 UTC
Tried to install BattleArena2 (BattleArena v3.9.9.13) on CraftBukkit version git-Spigot-fa7cbf9-00eba53 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT).

No other plugins installed.
Logged in as Op.
No permissions set, not even 'arena.join.arena'. I think that I tried on another server with this perm set (PEX) a couple of days ago, but it didn't help - still a NullpointerException.

Step-by-step (creating simple arena):
1. /arena create myarena
2. /arena alter myarena 2
3. /arena join myarena

However, when executing step 3 I get a null-pointer exception. Any ideas on how to resolve this issue.

Logs:
http://pastebin.com/CLkiWeTX

**Comment by Zach443** [comment] 2015-01-21 04:03
Duplicate of #7

**Comment by en3my** [comment] 2015-01-21 07:04
\messages\DefaultMessages.yml as follows:
http://pastebin.com/GHNibQff

messages.yml as follows:
http://pastebin.com/TVybjHHp

No changes in any of these files, using defualt values as generated when first starting the BattleArena-plugin.

**Comment by Europia79** [comment] 2015-01-21 21:19
Just talking to myself here, but the first line is not immediately clear which object is null and why: Either the argument passed in is null, or it has a null field. After looking into BScoreboard class, a null field seems to be impossible unless something is wrong with Spigot 1.8
https://github.com/Europia79/BattleScoreboardAPI/blob/master/src/java/mc/alk/scoreboardapi/scoreboard/bukkit/BObjective.java#L118
https://github.com/BattlePluginsDev/BattleArena/blob/master/src/java/mc/alk/arena/objects/scoreboard/ArenaObjective.java#L281
https://github.com/Europia79/BattleScoreboardAPI/blob/master/src/java/mc/alk/scoreboardapi/scoreboard/SAPIScoreboard.java#L38
https://github.com/BattlePluginsDev/BattleArena/blob/master/src/java/mc/alk/arena/objects/scoreboard/base/ArenaBukkitScoreboard.java#L74
https://github.com/BattlePluginsDev/BattleArena/blob/master/src/java/mc/alk/arena/objects/scoreboard/base/ArenaBukkitScoreboard.java#L68

Here on line 39 we get to a point where the parameters are definitely not null. However on line 37, null can be pass into the constructor:
https://github.com/BattlePluginsDev/BattleArena/blob/master/src/java/mc/alk/arena/controllers/joining/scoreboard/FullScoreboard.java#L39
Here is the call to the constructor: (args appear to be not null)
https://github.com/BattlePluginsDev/BattleArena/blob/master/src/java/mc/alk/arena/controllers/joining/AbstractJoinHandler.java#L117

At this point, i'm starting to think there's something wrong/different with Spigot. However, let's continue the stacktrace just in case:
https://github.com/BattlePluginsDev/BattleArena/blob/master/src/java/mc/alk/arena/controllers/joining/AbstractJoinHandler.java#L97

Line 96 is interesting: We could disable the scoreboard in the config.yml as a temporary solution until we find a permanent fix.

https://github.com/BattlePluginsDev/BattleArena/blob/master/src/java/mc/alk/arena/controllers/joining/AddToLeastFullTeam.java#L24

Here is more evidence that the MatchParams are NOT null: (we dispatch off them)
https://github.com/BattlePluginsDev/BattleArena/blob/master/src/java/mc/alk/arena/controllers/joining/TeamJoinFactory.java#L29
https://github.com/BattlePluginsDev/BattleArena/blob/master/src/java/mc/alk/arena/controllers/joining/TeamJoinFactory.java#L14
https://github.com/BattlePluginsDev/BattleArena/blob/master/src/java/mc/alk/arena/objects/joining/WaitingObject.java#L31
https://github.com/BattlePluginsDev/BattleArena/blob/master/src/java/mc/alk/arena/objects/joining/ArenaMatchQueue.java#L305
https://github.com/BattlePluginsDev/BattleArena/blob/master/src/java/mc/alk/arena/controllers/BattleArenaController.java#L252
Unfortunately, at this point, it appears that the stacktrace does not line up with the code.
https://github.com/BattlePluginsDev/BattleArena/blob/master/src/java/mc/alk/arena/executors/BAExecutor.java#L295
https://github.com/BattlePluginsDev/BattleArena/blob/master/src/java/mc/alk/arena/executors/BAExecutor.java#L198
https://github.com/BattlePluginsDev/BattleArena/blob/master/src/java/mc/alk/arena/executors/BAExecutor.java#L185
```
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
```
https://github.com/BattlePluginsDev/BattleArena/blob/master/src/java/mc/alk/arena/executors/BaseExecutor.java#L258
```
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
 at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645)
at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683)
at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
at java.lang.Thread.run(Unknown Source)
```

The log actually shows your MatchParams.

And the stack trace continues... (jumping down to caused by)
```
Caused by: java.lang.NullPointerException
 at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftCriteria.getFromNMS(CraftCriteria.java:42)
 at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftObjective.<init>(CraftObjective.java:19)
 at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftScoreboard.getObjective(CraftScoreboard.java:40)
```
back where we started originally:
https://github.com/alkarinv/BattleScoreboardAPI/blob/master/src/java/mc/alk/scoreboardapi/scoreboard/bukkit/BObjective.java#L118

But we see that it could actually be caused by the contents of your JAR.

Maybe you have mis-compiled the JAR... and you're missing one of the important patches...

This could be possibility since I cannot replicate this issue with my JARs.

Hmm... anyways, that's my analysis so far. I'll have to think about it.

Maybe you can send me your JAR ? And I can take a look at it. Or ask Spigot: How to tell if your JAR is good or not ?

**Comment by en3my** [comment] 2015-01-22 17:36
Thanks for looking into the issue and providing your thoughts! Today I downloaded the latest version of BattleArena and then rebuilt Spigot. It now works as expected. I believe that you were right about the JAR being mis-compiled.

Working as expected with:
- BattleArena v3.9.9.15
- CraftBukkit version git-Spigot-b1e6da1-1092acb (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT) (Build #25 (2015-Jan-20 22:32:09))

Thanks for the help and sorry for submitting an invalid issue!

**Comment by Zach443** [comment] 2015-01-22 23:27
No problem! It was refreshing to see someone submit an excellently formatted issue, with all the proper info. Keep doing doing what you're doing :+1:

**Closed** 2015-03-01 16:18 UTC
